In [1]:
import pandas as pd
import sklearn as sk
import numpy as np
import scipy as sp
from sklearn import tree
from sklearn.metrics import confusion_matrix

# Data Importing

In [2]:
#Importing dataset
car_train=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Car_Accidents_IOT/train.csv")
car_test=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Car_Accidents_IOT/test.csv")

In [3]:
features=list(car_train.columns[1:])
X_train=car_train[features]
y_train=car_train['Fatal']

# Decision Tree

In [4]:
###buildng Decision tree on the training data ####
clf = tree.DecisionTreeClassifier(max_depth=6)
clf.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

## Decision Tree Results

In [5]:
#####predicting on test data ####
tree_predict_train=clf.predict(car_train[features])
tree_predict=clf.predict(car_test[features])

########Train Data Validation
cm1 = confusion_matrix(car_train[['Fatal']],tree_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

########Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],tree_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)


Confusion Matrix for Train data 
 [[4940 1376]
 [ 688 8105]]
Accuracy of Train data 
 0.8633926798596863
Confusion Matrix for test data 
 [[2980  912]
 [ 389 4784]]
Accuracy of test data 
 0.8564809707666851


# Random Forest

In [6]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=20, max_features=4, max_depth=6)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=6, max_features=4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

## Random Forest Results

In [7]:
#####predicting on test data ####
Forest_predict_train=forest.predict(car_train[features])
Forest_predict=forest.predict(car_test[features])

########Train Data Validation
cm1 = confusion_matrix(car_train[['Fatal']],Forest_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

########Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],Forest_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)


Confusion Matrix for Train data 
 [[4752 1564]
 [ 516 8277]]
Accuracy of Train data 
 0.8623337083857303
Confusion Matrix for test data 
 [[2906  986]
 [ 338 4835]]
Accuracy of test data 
 0.8539437396580254
